version: "3.3"

services:
  mongodb-database:
    container_name: mongodb-database
    build: ./mongodb-image
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=test
  qix-engine:
    container_name: qix-engine
    image: qlikea/engine:12.90.0
    links:
      - mongodb-grpc-connector
    ports:
      - 9076:9076
      - 9090:9090
    command: --legacyreload -P 9076 -S SystemLogVerbosity=5 -S EnableGrpcCustomConnectors=1 -S GrpcConnectorPlugins="mongodb-grpc-connector,mongodb-grpc-connector:50051" -S EnableConnectivityService=0 -N
  mongodb-grpc-connector:
    container_name: mongodb-grpc-connector
    build: ../
    links:
      - mongodb-database
    ports:
      - 50051:50051
