version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/mongodb-grpc-connector
    steps:
      - checkout
      - restore_cache:
          key: npm-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install --quiet
      - run:
          name: Run ESLint
          command: npm run lint
      - save_cache:
          key: npm-dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - setup_remote_docker
      - run:
          name: Login to Docker
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - run:
          name: Spin up environment
          working_directory: ~/mongodb-grpc-connector/example
          command: ACCEPT_EULA=yes docker-compose up -d
      - run:
          name: Execute tests on remote dockers
          working_directory: ~/mongodb-grpc-connector/example/reload-runner
          command: |
            docker cp ./ node-test-runner:./reload-runner/
            docker exec node-test-runner sh -c 'npm install'
            docker exec node-test-runner sh -c 'TEST_HOST=qix-engine node index.js'
      - run:
          name: Build Docker Image
          command: |
            docker build .

